# Generated by Django 2.2.12 on 2021-03-16 06:40

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AugmentedParticipant',
            fields=[
                ('Participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='otree.Participant')),
                ('current_wp', otree.db.models.IntegerField(null=True)),
                ('outofthegame', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WPTimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', otree.db.models.StringField(max_length=10000, null=True)),
                ('page_index', otree.db.models.IntegerField(null=True)),
                ('startwp_timer_set', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('startwp_time', otree.db.models.PositiveIntegerField(null=True)),
                ('endwp_time', otree.db.models.PositiveIntegerField(null=True)),
                ('augmented_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavable_wait_page.AugmentedParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingRoomSlidersTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', otree.db.models.StringField(max_length=10000, null=True)),
                ('page_index', otree.db.models.IntegerField(null=True)),
                ('sliders_task_set', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('sliders_offsets', otree.db.models.StringField(max_length=10000, null=True)),
                ('sliders_curr_values', otree.db.models.StringField(max_length=10000, null=True)),
                ('sliders_for_task', otree.db.models.LongStringField(null=True)),
                ('num_centered_sliders', otree.db.models.IntegerField(null=True)),
                ('bonus_per_slider', otree.db.models.FloatField(null=True)),
                ('augmented_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavable_wait_page.AugmentedParticipant')),
            ],
        ),
    ]
