# Generated by Django 2.2.12 on 2021-03-26 13:39

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_s', '0002_auto_20210326_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tipo_votante',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
