# Generated by Django 2.2.12 on 2021-03-16 06:40

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Nombre:')),
                ('q2', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Email:')),
                ('q3', otree.db.models.StringField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10000, null=True, verbose_name='Género')),
                ('q4', otree.db.models.IntegerField(choices=[[1, 'Les alcanza bien y pueden ahorrar'], [2, 'Les alcanza justo y sin grandes dificultades'], [3, 'No les alcanza y tienen dificultades'], [4, 'No les alcanza y tienen grandes dificultades']], null=True, verbose_name='El salario o sueldo que usted recibe y el total del ingreso de su hogar')),
                ('q5', otree.db.models.IntegerField(choices=[[1, 'Menos de $288.800'], [2, 'Entre $288.801 - $312.001'], [3, 'Entre $312.002 - $361.002'], [4, 'Entre $361.003 - $410.003'], [5, 'Entre $410.004 - $459.004'], [6, 'Entre $459.005 - $558.005'], [7, 'Entre $558.006 - $657.006'], [8, 'Entre $657.007 - $756.007'], [9, 'Entre $756.008 - $1.005.008'], [10, 'Más de $1.005.008']], null=True, verbose_name='A continuación, hay varios rangos de ingresos. Indique en cuál de los siguientes rangos está el ingreso que usted personalmente gana al mes por su trabajo o pensión,sin contar el resto de los ingresos del hogar')),
                ('q6', otree.db.models.BooleanField(choices=[[1, 'Sí'], [0, 'No']], null=True, verbose_name='En este momento ¿simpatiza con algún partido político?')),
                ('q7', otree.db.models.IntegerField(choices=[[1, 'Partido Socialista de Chile'], [2, 'Unión Demócrata Independiente'], [3, 'Renovación Nacional'], [4, 'Partido Demócrata Cristiano'], [5, 'Partido Comunistica de Chile'], [6, 'Revolución Democrática'], [7, 'Evolución Política'], [8, 'Otro'], [9, 'No me siento representado']], null=True, verbose_name='¿Con cuál partido político simpatiza usted?')),
                ('q8', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Cambiando de tema, tenemos una escala de 1 a 10 que va de izquierda a derecha, en la que 1 significa izquierda y el 10 derecha. Hoy en día cuando se habla de tendencias políticas, mucha gente habla de aquellos que simpatizan más con la izquierda o con la derecha. Según el sentido que tengan para usted los términos "izquierda" y "derecha" cuando piensa sobre su punto de vista político, ¿dónde se encontraría usted en esta escala?. Marca el número que representa tu ideología política.')),
                ('q9', otree.db.models.BooleanField(choices=[[1, 'Sí'], [0, 'No']], null=True, verbose_name='Ahora pensando en las elecciones políticas, a cualquier cargo sujeto a votación popular, ¿Votaste en la última elección?')),
                ('q10', otree.db.models.BooleanField(choices=[[1, 'Sí'], [0, 'No']], null=True, verbose_name='¿Piensas votar en la próxima elección?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession')),
            ],
            options={
                'db_table': 'survey_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession'),
        ),
    ]
