# Generated by Django 2.2.12 on 2021-03-16 06:40

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('presupuesto', otree.db.models.IntegerField(default=0, null=True)),
                ('n_votantes', otree.db.models.IntegerField(default=0, null=True)),
                ('n_votantes_A', otree.db.models.IntegerField(default=0, null=True)),
                ('n_votantes_B', otree.db.models.IntegerField(default=0, null=True)),
                ('partido_elegido', otree.db.models.StringField(max_length=10000, null=True)),
                ('tipo_votante', otree.db.models.IntegerField(default=0, null=True)),
                ('ubicacion_pA', otree.db.models.IntegerField(default=0, null=True)),
                ('ubicacion_pB', otree.db.models.IntegerField(default=0, null=True)),
                ('pje_win_cA', otree.db.models.IntegerField(default=0, null=True)),
                ('pje_win_cB', otree.db.models.IntegerField(default=0, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_b_group', to='otree.Session')),
            ],
            options={
                'db_table': 'vote_b_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_b_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'vote_b_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('votanteOpartido', otree.db.models.StringField(max_length=10000, null=True)),
                ('tipoAoB', otree.db.models.StringField(max_length=10000, null=True)),
                ('nuevotipoAoB', otree.db.models.StringField(max_length=10000, null=True)),
                ('p_oferta_choice', otree.db.models.BooleanField(blank=True, choices=[[1, True], [0, False]], null=True)),
                ('p_oferta_amount', otree.db.models.IntegerField(default=0, null=True)),
                ('p_oferta_acepta', otree.db.models.IntegerField(blank=True, choices=[[1, 'Oferta del partido A.'], [2, 'Oferta del partido B.'], [3, 'Ninguna oferta.']], null=True)),
                ('win_lose', otree.db.models.StringField(max_length=10000, null=True)),
                ('puntos', otree.db.models.IntegerField(default=0, null=True)),
                ('avanza_vb_1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanza_vb_2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanza_vb_3', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanza_vb_4', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanza_vb_5', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote_b.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_b_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_b_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_b.Subsession')),
            ],
            options={
                'db_table': 'vote_b_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_b.Subsession'),
        ),
    ]
