# Generated by Django 2.2.12 on 2021-03-16 06:40

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_round_1_group', to='otree.Session')),
            ],
            options={
                'db_table': 'testing_round_1_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testing_round_1_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'testing_round_1_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1', otree.db.models.StringField(choices=[('Partido A', 'Partido A'), ('Partido B', 'Partido B')], max_length=10000, null=True, verbose_name='¿Qué partido ganó la votación?')),
                ('q2', otree.db.models.IntegerField(null=True, verbose_name='¿Cuántos puntos ganó el votante?')),
                ('q3', otree.db.models.IntegerField(null=True, verbose_name='¿Cuántos puntos ganó el partido A?')),
                ('q4', otree.db.models.IntegerField(null=True, verbose_name='¿Cuántos puntos ganó el partido B?')),
                ('q5', otree.db.models.StringField(choices=[('Partido A', 'Partido A'), ('Partido B', 'Partido B')], max_length=10000, null=True, verbose_name='¿Qué partido ganó la votación?')),
                ('q6', otree.db.models.IntegerField(null=True, verbose_name='¿Cuántos puntos ganó el votante?')),
                ('q7', otree.db.models.IntegerField(null=True, verbose_name='¿Cuántos puntos ganó el partido A?')),
                ('q8', otree.db.models.IntegerField(null=True, verbose_name='¿Cuántos puntos ganó el partido B?')),
                ('avanzo1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanzo2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanzo3', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanzo4', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('avanzo5', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing_round_1.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_round_1_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_round_1_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_round_1.Subsession')),
            ],
            options={
                'db_table': 'testing_round_1_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_round_1.Subsession'),
        ),
    ]
